version: '3.8'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PORT=3000
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=change-me
      - SESSION_SECRET=change-me-too
